Repository bobocode-blyznytsia/bring-framework, pull requests merged in 2023-02, with the labels that each got.

#33 Feature/issue 23/implement annotation bean definition reader
  pom.xml
  src/main/java/com/bringframework/annotations/Autowired.java
  src/main/java/com/bringframework/factory/RawBeanProcessor.java
  src/main/java/com/bringframework/reader/DefaultBeanDefinitionReader.java
  src/main/java/com/bringframework/registry/BeanDefinition.java
  src/main/java/com/bringframework/registry/BeanDefinitionImpl.java
  src/test/java/com/bringframework/factory/RawBeanProcessorTest.java
  src/test/java/com/bringframework/reader/DefaultBeanDefinitionReaderTest.java
  src/test/java/com/bringframework/reader/TestComponent.java
  src/test/java/com/bringframework/reader/TestService.java
  src/test/java/com/bringframework/util/BeanUtilsTest.java
Labels: enhancement

#53 [issue-#46, #47]: Exceptions refactoring
  src/main/java/com/bringframework/annotation/Autowired.java
  src/main/java/com/bringframework/annotation/Component.java
  src/main/java/com/bringframework/context/AnnotationConfigApplicationContext.java
  src/main/java/com/bringframework/exception/BeanDefinitionDuplicateNameException.java
  src/main/java/com/bringframework/exception/BeanInitializationException.java
  src/main/java/com/bringframework/exception/BeanInjectionException.java
  src/main/java/com/bringframework/exception/BringException.java
  src/main/java/com/bringframework/exception/NoSuchBeanException.java
  src/main/java/com/bringframework/exception/NoUniqueBeanException.java
  src/main/java/com/bringframework/exceptions/BeanDefinitionDuplicateNameException.java
  src/main/java/com/bringframework/exceptions/BeanInitializationException.java
  src/main/java/com/bringframework/exceptions/BeanInjectionException.java
  src/main/java/com/bringframework/exceptions/NoSuchBeanException.java
  src/main/java/com/bringframework/exceptions/NoUniqueBeanException.java
  src/main/java/com/bringframework/factory/AutowiredBeanPostProcessor.java
  src/main/java/com/bringframework/reader/BeanDefinitionReader.java
  src/main/java/com/bringframework/reader/ConfigBeanDefinitionReader.java
  src/main/java/com/bringframework/reader/DefaultBeanDefinitionReader.java
  src/main/java/com/bringframework/registry/DefaultBeanDefinitionRegistry.java
  src/main/java/com/bringframework/resolver/DefaultDependencyResolver.java
  src/main/java/com/bringframework/util/BeanUtils.java
  src/test/java/com/bringframework/context/AnnotationConfigApplicationContextTest.java
  src/test/java/com/bringframework/reader/TestComponent.java
  src/test/java/com/bringframework/registry/DefaultBeanDefinitionRegistryTest.java
  src/test/java/com/bringframework/resolver/DefaultDependencyResolverTest.java
  src/test/java/com/bringframework/util/BeanUtilsTest.java
Labels: refactoring

#54 Feature/issue 44/enhancements bring application appplication context
  src/main/java/com/bringframework/BringApplication.java
  src/main/java/com/bringframework/context/AnnotationConfigApplicationContext.java
  src/test/java/BringApplicationTest.java
  src/test/java/com/bringframework/context/AnnotationConfigApplicationContextTest.java
  src/test/java/com/bringframework/integration/BringApplicationIT.java
  src/test/java/com/bringframework/integration/service/ChatService.java
  src/test/java/com/bringframework/integration/service/GreetingService.java
  src/test/java/com/bringframework/integration/service/IMessageService.java
  src/test/java/com/bringframework/integration/service/MessageService.java
  src/test/java/com/bringframework/scanner/DefaultBeanDefinitionScannerTest.java
Labels: refactoring

#56 Feature/issue 48/add configuration of logger
  pom.xml
  src/main/resources/logback.xml
Labels: logging

#59 Feature/issue 28/implement config bean definition reader
  .gitignore
  src/main/java/com/bringframework/annotation/Bean.java
  src/main/java/com/bringframework/annotation/Component.java
  src/main/java/com/bringframework/annotation/Configuration.java
  src/main/java/com/bringframework/annotation/Qualifier.java
  src/main/java/com/bringframework/context/AnnotationConfigApplicationContext.java
  src/main/java/com/bringframework/context/ApplicationContext.java
  src/main/java/com/bringframework/exception/BeanDefinitionDuplicateNameException.java
  src/main/java/com/bringframework/exception/BeanInitializationException.java
  src/main/java/com/bringframework/exception/BeanInjectionException.java
  src/main/java/com/bringframework/exception/BringException.java
  src/main/java/com/bringframework/exception/NoSuchBeanException.java
  src/main/java/com/bringframework/factory/AutowiredBeanPostProcessor.java
  src/main/java/com/bringframework/factory/BeanFactoryImpl.java
  src/main/java/com/bringframework/factory/BeanProcessor.java
  src/main/java/com/bringframework/factory/ConfigBeanProcessor.java
  src/main/java/com/bringframework/factory/RawBeanProcessor.java
  src/main/java/com/bringframework/factory/impl/BeanFactoryImpl.java
  src/main/java/com/bringframework/registry/BeanDefinition.java
  src/main/java/com/bringframework/registry/BeanDefinitionImpl.java
  src/main/java/com/bringframework/registry/BeanDefinitionRegistry.java
  src/main/java/com/bringframework/registry/ConfigBeanDefinition.java
  src/main/java/com/bringframework/registry/DefaultBeanDefinitionRegistry.java
  src/main/java/com/bringframework/resolver/DefaultDependencyResolver.java
  src/main/java/com/bringframework/scanner/DefaultBeanDefinitionScanner.java
  src/main/java/com/bringframework/scanner/DefaultConfigBeanDefinitionScanner.java
  src/main/java/com/bringframework/util/BeanUtils.java
  src/test/java/com/bringframework/context/AnnotationConfigApplicationContextTest.java
  src/test/java/com/bringframework/factory/AutowiredBeanPostProcessorTest.java
  src/test/java/com/bringframework/factory/BeanFactoryImplTest.java
  src/test/java/com/bringframework/factory/ConfigBeanProcessorTest.java
  src/test/java/com/bringframework/factory/RawBeanProcessorTest.java
  src/test/java/com/bringframework/registry/DefaultBeanDefinitionRegistryTest.java
  src/test/java/com/bringframework/resolver/DefaultDependencyResolverTest.java
  src/test/java/com/bringframework/scanner/DefaultConfigBeanDefinitionScannerTest.java
  src/test/java/com/bringframework/scanner/TestConfiguration.java
  src/test/java/com/bringframework/util/BeanUtilsTest.java
Labels: bean-factory, bean-post-processor, bean-definition

#57 Feature/issue 29/get started guide
  README.md
  doc/bring.png
Labels: documentation
